spring:
    application:
        name: miniinsta
    data:
        redis:
            host: 172.18.243.18
            port: 6379
    datasource:
        url: jdbc:mysql://localhost:3306/miniinsta
        username: root
        password: thaihoc285 
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    rabbitmq:
        host: localhost
        port: 5672
        stomp:
            relay:
                host: localhost
                port: 61613
                login: guest
                passcode: guest
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 
                        client-secret: 
                        scope:
                            - email
                            - profile

springdoc:
    api-docs:
        path: /api-docs
logging:
    file:
        name: ./log/application.log
    level:
        org:
            springframework:
                jdbc:
                    core: DEBUG
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
---
spring.config.activate.on-profile: local
---
spring.config.activate.on-profile: docker-compose
spring:
    datasource:
        url: 'jdbc:mysql://mysql/app'
        username: app
        password: app
    data:
        redis:
            host: redis
            port: 6379
    rabbitmq:
        host: rabbitmq
        port: 5672
        stomp:
            relay:
                host: rabbitmq
                port: 61613
                login: guest
                passcode: guest